In [17]:
import nltk
print(nltk.__version__)

3.9.4

In [18]:
import numpy as np 
import pandas as pd

In [41]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [42]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [43]:
movies.dtypes

budget                    int64
genres                      str
homepage                    str
id                        int64
keywords                    str
original_language           str
original_title              str
overview                    str
popularity              float64
production_companies        str
production_countries        str
release_date                str
revenue                   int64
runtime                 float64
spoken_languages            str
status                      str
tagline                     str
title                       str
vote_average            float64
vote_count                int64
dtype: object

In [44]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [45]:
credits.dtypes

movie_id    int64
title         str
cast          str
crew          str
dtype: object

In [46]:
movies = movies.merge(credits,on="title")
movies.dtypes

budget                    int64
genres                      str
homepage                    str
id                        int64
keywords                    str
original_language           str
original_title              str
overview                    str
popularity              float64
production_companies        str
production_countries        str
release_date                str
revenue                   int64
runtime                 float64
spoken_languages            str
status                      str
tagline                     str
title                       str
vote_average            float64
vote_count                int64
movie_id                  int64
cast                        str
crew                        str
dtype: object

In [47]:
print(movies.columns)

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='str')

In [48]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [49]:
movies.rename(columns={'id': 'movie_id'}, inplace=True)

In [50]:
print("MOVIES COLUMNS:")
print(movies.columns)
print()

print("CREDITS COLUMNS:")
print(credits.columns)

MOVIES COLUMNS:
Index(['budget', 'genres', 'homepage', 'movie_id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='str')

CREDITS COLUMNS:
Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [51]:
movies = movies.loc[:, ~movies.columns.duplicated()]
print(movies.columns)

Index(['budget', 'genres', 'homepage', 'movie_id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew'],
      dtype='str')

In [52]:
movies = movies[['movie_id','title','genres','keywords','overview','cast','crew','release_date','runtime','tagline','budget','revenue']]

In [53]:
movies.isnull().sum()

movie_id          0
title             0
genres            0
keywords          0
overview          3
cast              0
crew              0
release_date      1
runtime           2
tagline         844
budget            0
revenue           0
dtype: int64

In [54]:
print(movies.dtypes)

movie_id          int64
title               str
genres              str
keywords            str
overview            str
cast                str
crew                str
release_date        str
runtime         float64
tagline             str
budget            int64
revenue           int64
dtype: object

In [55]:
# 1) For just the overview text
movies['overview'] = movies['overview'].fillna('')

# 2) For text-like columns: fill NaN with "Unknown"
text_cols = ['genres', 'keywords', 'cast', 'crew', 'tagline', 'title', 'release_date']
movies[text_cols] = movies[text_cols].fillna('Unknown')

# 3) For numeric columns: fill NaN with numeric values
movies['runtime'] = movies['runtime'].fillna(movies['runtime'].median())
movies['budget']  = movies['budget'].fillna(0)
movies['revenue'] = movies['revenue'].fillna(0)

In [56]:
movies.isnull().sum()

movie_id        0
title           0
genres          0
keywords        0
overview        0
cast            0
crew            0
release_date    0
runtime         0
tagline         0
budget          0
revenue         0
dtype: int64

In [57]:
movies.duplicated().sum()

np.int64(0)

In [58]:
import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [59]:
movies.head(1)

,movie_id,title,genres,keywords,overview,cast,crew,release_date,runtime,tagline,budget,revenue
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10,162.0,Enter the World of Pandora.,237000000,2787965087

In [62]:
movies.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [63]:
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [64]:
movies.iloc[0]['genres']

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [65]:
def convert5(obj):
    c = 0
    L = []
    for i in ast.literal_eval(obj):
        if c != 5:
            L.append(i['name'])
            c=+1
        else:
            break
    return L

In [66]:
movies['cast'] = movies['cast'].apply(convert5)

In [67]:
def fetch_dir(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [68]:
movies['crew'] = movies['crew'].apply(fetch_dir)

In [69]:
o = movies['overview'].apply(lambda x:x.split())
g = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
k = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
c = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
d = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

movies["tag"] = o+g+k+c+d

In [70]:
movies['tag'] = movies['tag'].apply(lambda x:" ".join(x))

In [71]:
movies['tag'] = movies['tag'].apply(lambda x:x.lower())

In [78]:
new = movies[['movie_id','title','tag']]

In [79]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [80]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [85]:
print(new.head(1)['tag'])

0    in the 22nd century, a paraplegic marine is di...
Name: tag, dtype: str

In [86]:
new['tag'] = new['tag'].apply(stem)
new

,movie_id,title,tag
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [87]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [88]:
vectors = cv.fit_transform(new['tag']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4809, 5000))

In [90]:
vectors[0][2864:2867]

array([0, 2, 0])

In [89]:
vocab = cv.vocabulary_
print(vocab)

{'century': np.int64(725), 'marin': np.int64(2865), 'dispatch': np.int64(1272), 'moon': np.int64(3117), 'uniqu': np.int64(4733), 'mission': np.int64(3091), 'becom': np.int64(411), 'torn': np.int64(4617), 'follow': np.int64(1668), 'order': np.int64(3320), 'protect': np.int64(3588), 'alien': np.int64(147), 'action': np.int64(58), 'adventur': np.int64(89), 'fantasi': np.int64(1594), 'sciencefict': np.int64(4014), 'cultureclash': np.int64(1049), 'futur': np.int64(1749), 'societi': np.int64(4222), 'spacetravel': np.int64(4260), 'futurist': np.int64(1751), 'romanc': np.int64(3884), 'space': np.int64(4254), 'tribe': np.int64(4665), 'soldier': np.int64(4229), 'battl': np.int64(394), '3d': np.int64(30), 'samworthington': np.int64(3972), 'zoesaldana': np.int64(4993), 'sigourneyweav': np.int64(4157), 'stephenlang': np.int64(4319), 'michellerodriguez': np.int64(3039), 'giovanniribisi': np.int64(1811), 'lazalonso': np.int64(2657), 'scottlawr': np.int64(4026), 'mil': np.int64(3061), 'hunt': np.int64(2078), 'storm': np.int64(4346), 'bailey': np.int64(359), 'captain': np.int64(662), 'long': np.int64(2755), 'believ': np.int64(422), 'dead': np.int64(1139), 'ha': np.int64(1898), 'come': np.int64(907), 'life': np.int64(2712), 'head': np.int64(1958), 'edg': np.int64(1387), 'earth': np.int64(1371), 'turner': np.int64(4686), 'elizabeth': np.int64(1420), 'noth': np.int64(3263), 'quit': np.int64(3622), 'ocean': np.int64(3283), 'drugabus': np.int64(1335), 'exoticisland': np.int64(1546), 'loveofone': np.int64(2783), 'slif': np.int64(4203), 'traitor': np.int64(4644), 'shipwreck': np.int64(4138), 'ship': np.int64(4137), 'allianc': np.int64(158), 'afterlif': np.int64(101), 'fighter': np.int64(1631), 'pirat': np.int64(3465), 'aftercreditssting': np.int64(100), 'johnnydepp': np.int64(2412), 'orlandobloom': np.int64(3326), 'keiraknightley': np.int64(2527), 'stellanskarsgård': np.int64(4311), 'fat': np.int64(1603), 'billnighi': np.int64(468), 'geoffreyrush': np.int64(1786), 'kevinmcn': np.int64(2552), 'tomholland': np.int64(4589), 'naomieharri': np.int64(3175), 'jonathanpryc': np.int64(2432), 'mackenziecrook': np.int64(2814), 'martinklebba': np.int64(2904), 'reggiele': np.int64(3718), 'ho': np.int64(2013), 'messag': np.int64(2985), 'bond': np.int64(531), 'past': np.int64(3377), 'send': np.int64(4082), 'trail': np.int64(4641), 'uncov': np.int64(4713), 'sinist': np.int64(4177), 'polit': np.int64(3500), 'forc': np.int64(1676), 'secret': np.int64(4053), 'servic': np.int64(4099), 'alive': np.int64(152), 'deceit': np.int64(1155), 'reveal': np.int64(3783), 'terribl': np.int64(4499), 'truth': np.int64(4680), 'crime': np.int64(1024), 'spi': np.int64(4275), 'basedonnovel': np.int64(383), 'secretag': np.int64(4054), 'sequel': np.int64(4089), 'britishsecretservic': np.int64(591), 'danielcraig': np.int64(1080), 'christophwaltz': np.int64(824), 'ralphfienn': np.int64(3651), 'monicabellucci': np.int64(3110), 'benwhishaw': np.int64(441), 'judidench': np.int64(2474), 'death': np.int64(1146), 'district': np.int64(1274), 'attorney': np.int64(328), 'harvey': np.int64(1946), 'batman': np.int64(393), 'assum': np.int64(317), 'respons': np.int64(3770), 'late': np.int64(2639), 'reput': np.int64(3760), 'gotham': np.int64(1836), 'citi': np.int64(834), 'polic': np.int64(3493), 'year': np.int64(4978), 'later': np.int64(2640), 'encount': np.int64(1458), 'mysteri': np.int64(3168), 'kyle': np.int64(2608), 'villain': np.int64(4799), 'new': np.int64(3217), 'terrorist': np.int64(4502), 'leader': np.int64(2660), 'overwhelm': np.int64(3340), 'dark': np.int64(1096), 'knight': np.int64(2588), 'brand': np.int64(558), 'enemy': np.int64(1463), 'drama': np.int64(1318), 'thriller': np.int64(4537), 'dccomic': np.int64(1137), 'crimefight': np.int64(1025), 'secretident': np.int64(4056), 'vigilant': np.int64(4796), 'cover': np.int64(1004), 'superhero': np.int64(4403), 'terror': np.int64(4501), 'destruct': np.int64(1219), 'imax': np.int64(2111), 'flood': np.int64(1659), 'christianbal': np.int64(806), 'michaelcain': np.int64(3004), 'garyoldman': np.int64(1775), 'annehathaway': np.int64(239), 'tomhardi': np.int64(4588), 'marioncotillard': np.int64(2866), 'josephgordon': np.int64(2450), 'levitt': np.int64(2699), 'morganfreeman': np.int64(3121), 'cillianmurphi': np.int64(829), 'junotempl': np.int64(2492), 'liamneeson': np.int64(2705), 'benmendelsohn': np.int64(437), 'joeyk': np.int64(2381), 'brettcullen': np.int64(570), 'chriselli': np.int64(792), 'thomaslennon': np.int64(4530), 'brentbrisco': np.int64(568), 'noelgugliemi': np.int64(3254), 'tomasarana': np.int64(4581), 'johnw': np.int64(2424), 'brien': np.int64(585), 'michaelpapajohn': np.int64(3026), 'markfalvo': np.int64(2873), 'john': np.int64(2383), 'carter': np.int64(692), 'war': np.int64(4849), 'militari': np.int64(3066), 'inexplic': np.int64(2136), 'transport': np.int64(4648), 'exot': np.int64(1545), 'planet': np.int64(3472), 'reluctantli': np.int64(3741), 'embroil': np.int64(1440), 'epic': np.int64(1483), 'conflict': np.int64(940), 'world': np.int64(4956), 'brink': np.int64(588), 'hi': np.int64(1985), 'human': np.int64(2068), 'realiz': np.int64(3688), 'surviv': np.int64(4424), 'peopl': np.int64(3418), 'rest': np.int64(3771), 'hands': np.int64(1913), 'mar': np.int64(2852), 'princess': np.int64(3560), 'martian': np.int64(2899), 'escap': np.int64(1498), '19thcenturi': np.int64(24), 'samanthamorton': np.int64(3963), 'willemdafo': np.int64(4908), 'thomashadenchurch': np.int64(4527), 'markstrong': np.int64(2879), 'ciaránhind': np.int64(828), 'dominicwest': np.int64(1296), 'bryancranston': np.int64(614), 'darylsabara': np.int64(1100), 'seemingli': np.int64(4071), 'spider': np.int64(4276), 'man': np.int64(2840), 'goe': np.int64(1825), 'includ': np.int64(2124), 'shape': np.int64(4121), 'shift': np.int64(4136), 'superpow': np.int64(4409), 'alter': np.int64(165), 'ego': np.int64(1404), 'peter': np.int64(3429), 'parker': np.int64(3365), 'deal': np.int64(1142), 'eddi': np.int64(1380), 'caught': np.int64(712), 'love': np.int64(2781), 'dualident': np.int64(1344), 'amnesia': np.int64(188), 'forgiv': np.int64(1687), 'wretch': np.int64(4967), 'deathofafriend': np.int64(1147), 'sand': np.int64(3975), 'hostil': np.int64(2051), 'marvelcom': np.int64(2912), 'reveng': np.int64(3785), 'tobeymaguir': np.int64(4569), 'kirstendunst': np.int64(2582), 'jamesfranco': np.int64(2241), 'tophergrac': np.int64(4615), 'brycedallashoward': np.int64(616), 'jamescromwel': np.int64(2237), 'simmon': np.int64(4162), 'dylanbak': np.int64(1360), 'billnunn': np.int64(469), 'elizabethbank': np.int64(1421), 'tedraimi': np.int64(4480), 'stanle': np.int64(4300), 'brucecampbel': np.int64(606), 'jon': np.int64(2427), 'thoma': np.int64(4525), 'ward': np.int64(4851), 'samraimi': np.int64(3966), 'kingdom': np.int64(2579), 'flynn': np.int64(1663), 'hide': np.int64(1987), 'tower': np.int64(4627), 'taken': np.int64(4449), 'hostag': np.int64(2049), 'beauti': np.int64(404), 'bound': np.int64(541), 'teen': np.int64(4481), '70': np.int64(34), 'feet': np.int64(1616), 'golden': np.int64(1827), 'hair': np.int64(1901), 'look': np.int64(2758), 'ticket': np.int64(4545), 'lock': np.int64(2747), 'away': np.int64(346), 'years': np.int64(4980), 'strike': np.int64(4360), 'handsom': np.int64(1914), 'thief': np.int64(4520), 'unlik': np.int64(4740), 'duo': np.int64(1349), 'set': np.int64(4100), 'pack': np.int64(3345), 'complet': np.int64(929), 'super': np.int64(4402), 'cop': np.int64(975), 'gang': np.int64(1763), 'anim': np.int64(224), 'famili': np.int64(1586), 'magic': np.int64(2822), 'hors': np.int64(2045), 'fairytal': np.int64(1577), 'music': np.int64(3160), 'duringcreditssting': np.int64(1351), 'mandymoor': np.int64(2842), 'ronperlman': np.int64(3897), 'gainey': np.int64(1757), 'jeffreytambor': np.int64(2305), 'bradgarrett': np.int64(552), 'toni': np.int64(4604), 'tri': np.int64(4662), 'program': np.int64(3575), 'thing': np.int64(4522), 'awri': np.int64(347), 'hero': np.int64(1981), 'ultim': np.int64(4706), 'test': np.int64(4506), 'fate': np.int64(1605), 'hang': np.int64(1916), 'aveng': np.int64(341), 'stop': np.int64(4341), 'plans': np.int64(3474), 'soon': np.int64(4240), 'unexpect': np.int64(4725), 'way': np.int64(4867), 'global': np.int64(1821), 'adventure': np.int64(90), 'basedoncomicbook': np.int64(381), 'vision': np.int64(4819), 'marvelcinematicunivers': np.int64(2911), 'robertdowneyjr': np.int64(3846), 'chrishemsworth': np.int64(794), 'markruffalo': np.int64(2878), 'chrisevan': np.int64(793), 'scarlettjohansson': np.int64(4004), 'jeremyrenn': np.int64(2321), 'jamesspad': np.int64(2252), 'samuell': np.int64(3970), 'jackson': np.int64(2218), 'doncheadl': np.int64(1301), 'aarontaylor': np.int64(37), 'johnson': np.int64(2421), 'paulbettani': np.int64(3397), 'anthonymacki': np.int64(256), 'idriselba': np.int64(2097), 'thomaskretschmann': np.int64(4529), 'andyserki': np.int64(215), 'kim': np.int64(2573), 'clark': np.int64(846), 'joshbrolin': np.int64(2454), 'nicholson': np.int64(3232), 'harri': np.int64(1934), 'begin': np.int64(419), 'discov': np.int64(1263), 'old': np.int64(3291), 'book': np.int64(534), 'mark': np.int64(2869), 'properti': np.int64(3582), 'half': np.int64(1904), 'blood': np.int64(502), 'prince': np.int64(3559), 'learn': np.int64(2663), 'lord': np.int64(2761), 'witch': np.int64(4936), 'teenagecrush': np.int64(4483), 'werewolf': np.int64(4884), 'danielradcliff': np.int64(1083), 'emmawatson': np.int64(1451), 'tomfelton': np.int64(4586), 'michaelgambon': np.int64(3012), 'jimbroadb': np.int64(2347), 'helenabonhamcart': np.int64(1973), 'robbiecoltran': np.int64(3839), 'maggiesmith': np.int64(2821), 'alanrickman': np.int64(125), 'timothyspal': np.int64(4561), 'davidthewli': np.int64(1130), 'juliewalt': np.int64(2487), 'markwilliam': np.int64(2882), 'warwickdavi': np.int64(4858), 'geraldinesomervil': np.int64(1796), 'davidbradley': np.int64(1113), 'ralphineson': np.int64(3652), 'fear': np.int64(1612), 'god': np.int64(1824), 'lik': np.int64(2718), 'left': np.int64(2669), 'city': np.int64(836), 'modern': np.int64(3105), 'day': np.int64(1135), 'wrestl': np.int64(4966), 'sort': np.int64(4246), 'realli': np.int64(3689), 'superman': np.int64(4405), 'threat': np.int64(4534), 'quickli': np.int64(3618), 'mankind': np.int64(2848), 'greater': np.int64(1852), 'danger': np.int64(1076), 'known': np.int64(2592), 'benaffleck': np.int64(427), 'amyadam': np.int64(192), 'jesseeisenberg': np.int64(2328), 'dianelan': np.int64(1237), 'jeremyiron': np.int64(2318), 'laurencefishburn': np.int64(2647), 'hollyhunt': np.int64(2019), 'scootmcnairi': np.int64(4017), 'jenamalon': np.int64(2307), 'harrylennix': np.int64(1941), 'kevincostn': np.int64(2546), 'patrickwilson': np.int64(3392), 'michaelshannon': np.int64(3033), 'jonstewart': np.int64(2442), 'carlagugino': np.int64(678), 'joemorton': np.int64(2375), 'adam': np.int64(64), 'patricko': np.int64(3389), 'brown': np.int64(604), 'return': np.int64(3780), 'allow': np.int64(160), 'walk': np.int64(4836), 'free': np.int64(1728), 'wa': np.int64(4830), 'abandon': np.int64(39), 'plot': np.int64(3484), 'million': np.int64(3069), 'kill': np.int64(2569), 'chang': np.int64(736), 'face': np.int64(1569), 'forever': np.int64(1684), 'rid': np.int64(3814), 'steel': np.int64(4310), 'savingtheworld': np.int64(3995), 'kevinspacey': np.int64(2557), 'katebosworth': np.int64(2507), 'jamesmarsden': np.int64(2247), 'parkerposey': np.int64(3366), 'franklangella': np.int64(1712), 'marlonbrando': np.int64(2884), 'kalpenn': np.int64(2499), 'bryansing': np.int64(615), 'continu': np.int64(965), 'jame': np.int64(2229), 'casino': np.int64(698), 'betray': np.int64(451), 'woman': np.int64(4939), '007': np.int64(1), 'fight': np.int64(1630), 'make': np.int64(2829), 'latest': np.int64(2641), 'pursu': np.int64(3608), 'determin': np.int64(1223), 'interrog': np.int64(2172), 'mr': np.int64(3147), 'white': np.int64(4896), 'organ': np.int64(3323), 'blackmail': np.int64(492), 'far': np.int64(1597), 'complex': np.int64(930), 'anyon': np.int64(263), 'undercov': np.int64(4715), 'olgakurylenko': np.int64(3296), 'gemmaarterton': np.int64(1779), 'jeffreywright': np.int64(2306), 'davidharbour': np.int64(1118), 'timpigott': np.int64(4562), 'smith': np.int64(4209), 'jack': np.int64(2206), 'work': np.int64(4951), 'debt': np.int64(1151), 'jones': np.int64(2436), 'attempt': np.int64(324), 'avoid': np.int64(342), 'etern': np.int64(1506), 'monster': np.int64(3113), 'daughter': np.int64(1103), 'texa': np.int64(4507), 'ranger': np.int64(3660), 'chase': np.int64(758), 'outlaw': np.int64(3336), 'led': np.int64(2665), 'ambush': np.int64(181), 'survivor': np.int64(4427), 'american': np.int64(184), 'indian': np.int64(2131), 'nurs': np.int64(3274), 'health': np.int64(1960), 'don': np.int64(1297), 'mask': np.int64(2922), 'ride': np.int64(3816), 'silver': np.int64(4160), 'team': np.int64(4474), 'bring': np.int64(587), 'justice': np.int64(2495), 'western': np.int64(4890), 'partner': np.int64(3371), 'lawyer': np.int64(2654), 'train': np.int64(4642), 'williamfichtn': np.int64(4913), 'jamesbadgedal': np.int64(2231), 'tomwilkinson': np.int64(4603), 'barrypepp': np.int64(376), 'jamesfrain': np.int64(2240), 'matto': np.int64(2943), 'leari': np.int64(2662), 'earlbrown': np.int64(1367), 'murphi': np.int64(3156), 'lewtempl': np.int64(2701), 'stephenroot': np.int64(4322), 'rancehoward': np.int64(3655), 'hil': np.int64(1995), 'young': np.int64(4982), 'boy': np.int64(546), 'extraordinari': np.int64(1561), 'power': np.int64(3523), 'thi': np.int64(4519), 'journey': np.int64(2464), 'came': np.int64(645), 'sent': np.int64(4085), 'emerg': np.int64(1441), 'save': np.int64(3994), 'symbol': np.int64(4444), 'hope': np.int64(2038), 'superhuman': np.int64(4404), 'alieninvas': np.int64(148), 'russellcrow': np.int64(3932), 'christophermeloni': np.int64(820), 'richardschiff': np.int64(3809), 'michaelkelli': np.int64(3019), 'richardcetron': np.int64(3797), 'julianrich': np.int64(2481), 'incred': np.int64(2127), 'lion': np.int64(2729), 'luci': np.int64(2795), 'susan': np.int64(4428), 'aid': np.int64(114), 'princ': np.int64(3558), 'threaten': np.int64(4535), 'evil': np.int64(1529), 'king': np.int64(2578), 'help': np.int64(1978), 'color': np.int64(903), 'cast': np.int64(699), 'characters': np.int64(743), 'clan': np.int64(844), 'embark': np.int64(1438), 'quest': np.int64(3615), 'right': np.int64(3819), 'heir': np.int64(1968), 'fictionalplac': np.int64(1627), 'brothersisterrelationship': np.int64(602), 'faith': np.int64(1578), 'uncl': np.int64(4710), 'fantasyworld': np.int64(1596), 'peterdinklag': np.int64(3434), 'tildaswinton': np.int64(4548), 'eddieizzard': np.int64(1383), 'enemi': np.int64(1461), 'safeti': np.int64(3952), 'nick': np.int64(3233), 'director': np.int64(1257), 'intern': np.int64(2170), 'need': np.int64(3201), 'pull': np.int64(3602), 'disaster': np.int64(1262), 'span': np.int64(4262), 'globe': np.int64(1822), 'dare': np.int64(1095), 'recruit': np.int64(3707), 'effort': np.int64(1402), 'newyork': np.int64(3226), 'clarkgregg': np.int64(847), 'gwynethpaltrow': np.int64(1894), 'powersbooth': np.int64(3526), 'harrydeanstanton': np.int64(1940), 'robertclohessi': np.int64(3843), 'william': np.int64(4912), 'patkiernan': np.int64(3382), 'cross': np.int64(1035), 'path': np.int64(3379), 'sure': np.int64(4415), 'ruthless': np.int64(3937), 'artist': np.int64(303), 'use': np.int64(4757), 'fabl': np.int64(1567), 'youth': np.int64(4986), 'queen': np.int64(3612), 'anne': np.int64(236), 'revenge': np.int64(3786), 'doesn': np.int64(1287), 'know': np.int64(2590), 'sea': np.int64(4035), 'mutini': np.int64(3165), 'sword': np.int64(4439), 'sail': np.int64(3955), 'duke': np.int64(1347), 'mermaid': np.int64(2983), 'penélopecruz': np.int64(3417), 'ianmcshan': np.int64(2087), 'stephengraham': np.int64(4318), 'har': np.int64(1924), 'richardgriffith': np.int64(3802), 'derekmear': np.int64(1203), 'moor': np.int64(3119), 'agent': np.int64(109), 'tommi': np.int64(4594), 'lee': np.int64(2666), 'time': np.int64(4554), 'seen': np.int64(4072), '15': np.int64(8), 'men': np.int64(2977), 'black': np.int64(490), 'stake': np.int64(4295), 'travel': np.int64(4652), 'univers': np.int64(4735), 'told': np.int64(4578), 'themselv': np.int64(4516), 'josh': np.int64(2453), 'agency': np.int64(107), 'humankind': np.int64(2070), 'comedi': np.int64(909), 'timetravel': np.int64(4556), 'willsmith': np.int64(4922), 'tommyleejon': np.int64(4596), 'emmathompson': np.int64(1450), 'billhad': np.int64(463), 'willarnett': np.int64(4907), 'immedi': np.int64(2113), 'event': np.int64(1519), 'desol': np.int64(1210), 'defend': np.int64(1167), 'mountain': np.int64(3139), 'treasur': np.int64(4654), 'claim': np.int64(840), 'ruin': np.int64(3920), 'elv': np.int64(1436), 'meanwhil': np.int64(2958), 'armi': np.int64(288), 'orc': np.int64(3319), 'march': np.int64(2854), 'fuel': np.int64(1743), 'rise': np.int64(3826), 'middle': np.int64(3046), 'fall': np.int64(1581), 'corrupt': np.int64(984), 'dragon': np.int64(1317), 'swordandsorceri': np.int64(4440), 'martinfreeman': np.int64(2903), 'ianmckellen': np.int64(2086), 'leepac': np.int64(2668), 'cateblanchett': np.int64(705), 'hugoweav': np.int64(2067), 'christopherle': np.int64(817), 'ianholm': np.int64(2085), 'stephenfri': np.int64(4317), 'billyconnolli': np.int64(474), 'benedictcumberbatch': np.int64(430), 'peterjackson': np.int64(3437), 'outcast': np.int64(3334), 'high': np.int64(1988), 'parent': np.int64(3359), 'leav': np.int64(2664), 'rais': np.int64(3647), 'ben': np.int64(426), 'aunt': np.int64(334), 'like': np.int64(2719), 'figur': np.int64(1632), 'got': np.int64(1835), 'person': np.int64(3424), 'today': np.int64(4574), 'belong': np.int64(424), 'father': np.int64(1606), 'understand': np.int64(4721), 'parents': np.int64(3360), 'disappear': np.int64(1260), 'lead': np.int64(2659), 'dr': np.int64(1314), 'collis': np.int64(898), 'cours': np.int64(997), 'choic': np.int64(785), 'destini': np.int64(1215), 'lossoffath': np.int64(2769), 'emmaston': np.int64(1449), 'rhysifan': np.int64(3794), 'denisleari': np.int64(1183), 'irrfankhan': np.int64(2194), 'martinsheen': np.int64(2908), 'embethdavidtz': np.int64(1439), 'tomwait': np.int64(4602), 'keithcampbel': np.int64(2528), 'vincentlaresca': np.int64(4803), 'robin': np.int64(3857), 'happen': np.int64(1919), 'die': np.int64(1245), 'robert': np.int64(3842), 'promis': np.int64(3579), 'identity': np.int64(2095), 'widow': np.int64(4899), 'draw': np.int64(1320), 'town': np.int64(4628), 'sheriff': np.int64(4133), 'middleag': np.int64(3047), 'mediev': np.int64(2963), 'maxvonsydow': np.int64(2951), 'williamhurt': np.int64(4916), 'oscarisaac': np.int64(3332), 'dannyhuston': np.int64(1090), 'markaddi': np.int64(2870), 'kevindurand': np.int64(2548), 'simonmcburney': np.int64(4166), 'ridleyscott': np.int64(3817), 'success': np.int64(4383), 'gain': np.int64(1756), 'ring': np.int64(3822), 'gold': np.int64(1826), 'wizard': np.int64(4937), 'shock': np.int64(4140), 'orphan': np.int64(3329), 'trade': np.int64(4635), 'exist': np.int64(1541), 'hall': np.int64(1906), 'jordan': np.int64(2445), 'colleg': np.int64(894), 'north': np.int64(3261), 'unawar': np.int64(4709), 'destiny': np.int64(1216), 'england': np.int64(1468), 'experi': np.int64(1550), 'basedonyoungadultnovel': np.int64(390), 'nicolekidman': np.int64(3243), 'samelliott': np.int64(3964), 'freddiehighmor': np.int64(1723), 'kristinscottthoma': np.int64(2601), 'kathyb': np.int64(2518), 'derekjacobi': np.int64(1201), 'york': np.int64(4981), 'ambiti': np.int64(179), 'movi': np.int64(3143), 'produc': np.int64(3570), 'hire': np.int64(2003), 'crew': np.int64(1023), 'skull': np.int64(4193), 'island': np.int64(2197), 'kong': np.int64(2593), 'giant': np.int64(1806), 'ape': np.int64(268), 'smitten': np.int64(4210), 'filmmak': np.int64(1635), 'filmproduc': np.int64(1636), 'dinosaur': np.int64(1255), 'naomiwatt': np.int64(3176), 'jackblack': np.int64(2207), 'adrienbrodi': np.int64(84), 'colinhank': np.int64(887), 'jamiebel': np.int64(2255), 'kylechandl': np.int64(2609), 'rose': np.int64(3907), 'tell': np.int64(4490), 'stor

In [91]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [92]:
print(similarity)

[[1.         0.06666667 0.07559289 ... 0.04259177 0.         0.        ]
 [0.06666667 1.         0.07559289 ... 0.02129589 0.         0.02357023]
 [0.07559289 0.07559289 1.         ... 0.02414726 0.         0.        ]
 ...
 [0.04259177 0.02129589 0.02414726 ... 1.         0.04307305 0.0451754 ]
 [0.         0.         0.         ... 0.04307305 1.         0.09534626]
 [0.         0.02357023 0.         ... 0.0451754  0.09534626 1.        ]]

In [27]:
import pickle
pickle.dump(movies,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [94]:
pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.5-cp314-cp314-win_amd64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.5-cp314-cp314-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.6 MB 668.7 kB/s eta 0:00:02
   ------------------- -------------------- 0.8/1.6 MB 789.1 kB/s eta 0:00:02
   -------------------------- ------------- 1.0/1.6 MB 924.5 kB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 1.1 MB/s  0:00:01
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
from rapidfuzz import process

def recommend(movie):
    movie_titles = movies['title'].tolist()

    match, score, _ = process.extractOne(movie, movie_titles)

    if score < 50:
        print("Movie not found")
        return

    print(f"\nRecommendations for '{match}':\n")

    index = movies[movies['title'] == match].index[0]

    distances = sorted(
        list(enumerate(similarity[index])),
        key=lambda x: x[1],
        reverse=True
    )

    for i in distances[1:6]:
        print("•", new.iloc[i[0]]['title'])

In [95]:
from rapidfuzz import process

def recommend(movie):
    # Ensure consistent dataframe reference (using 'movies')
    movie_titles = movies['title'].tolist()

    # Find the single best fuzzy match
    match, score, _ = process.extractOne(movie, movie_titles)

    if score < 50:
        print("Movie not found")
        return

    print(f"\nRecommendations for '{match}':\n")

    # Get the index of the matched movie
    index = movies[movies['title'] == match].index[0]

    # Get the top 5 most similar movies (excluding the movie itself at index 0)
    # Using key=lambda x: x[1] assumes your similarity matrix holds scores where higher = more similar
    distances = sorted(
        enumerate(similarity[index]),
        key=lambda x: x[1],
        reverse=True
    )[1:6]

    # Print the recommendations using the same 'movies' dataframe
    for i in distances:
        print("•", movies.iloc[i[0]]['title'])

In [99]:
recommend(" Diaries")

Recommendations for 'The Princess Diaries 2: Royal Engagement':

• The Princess Diaries
• Raising Helen
• Georgia Rule
• Stop-Loss
• My Girl

In [102]:
print(new.columns)

Index(['movie_id', 'title', 'tag'], dtype='str')

In [103]:
movie_data = new[['movie_id', 'title', 'tag']].merge(
    movies[['movie_id', 'overview']],
    on='movie_id',
    how='left'
)

In [104]:
import pickle

movie_dict = movie_data.to_dict(orient='records')

pickle.dump(movie_dict, open('movie_list.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [106]:
movie_data = movies[['movie_id', 'title', 'overview', 'tag']].copy()
movie_data = movie_data.rename(columns={'movie_id': 'movie_id'})

import pickle
pickle.dump(movie_data.to_dict(orient='records'), open('movie_list.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))

print("done")
print(movie_data.columns)
print(movie_data.head(2))

done
Index(['movie_id', 'title', 'overview', 'tag'], dtype='str')
   movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...

                                                 tag
0  in the 22nd century, a paraplegic marine is di...
1  captain barbossa, long believed to be dead, ha...